services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:2.7
    container_name: music-assistant-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - /storage/appdata/music-assistant:/data/
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      - LOG_LEVEL=info
